=== Dak0r/TextAdventureJS/textAdventureDatabase.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "textAdventure Game Database",
  "description": "A game database for textAdventureJS",
  "definitions": {
    "action_definition": {
      "description": "Defines what happens if a verb is used (with this object / in this location)",
      "type": "object",
      "required": ["text", "action"],
      "properties": {
        "text": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "action": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "general": {
      "description": "General Information about this tbe database",
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "author": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "request": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "start": {
          "$ref": "#/definitions/action_definition"
        }
      },
      "required": ["title", "author", "version", "request", "start"]
    },
    "ignored_words" : {
      "description": "Words that will be ignored when parsing an user input. This prevent that they get interpreted as verbs or objects (Note: Thus objects and names can't have this as on of their 'words')",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "verbs": {
      "description": "List of verbs that are available throughout the game",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "required": ["failure", "words"],
        "properties": {
          "failure": {
            "type": "string"
          },
          "words": {
            "description": "Alternative words that the player may use",
            "type": "array",
            "items": { "type": "string" },
            "minItems": 1,
            "uniqueItems": true
          }
        }
      }
    },
    "objects": {
      "description": "List of objecs that are available throughout the game",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "required": [
          "words",
          "locationDescription",
          "actions",
          "useableObjects"
        ],
        "properties": {
          "words": {
            "description": "Alternative words that the player may use",
            "type": "array",
            "items": { "type": "string" },
            "minItems": 1,
            "uniqueItems": true
          },
          "locationDescription": {
            "type": "string"
          },
          "actions": {
            "description": "List of verbs that can be used with this object and what should happen",
            "type": "object",
            "additionalProperties": {
              "$ref": "#/definitions/action_definition"
            }
          },
          "useableObjects": {
            "description": "List of possible combinations",
            "type": "object",
            "additionalProperties": {
              "$ref": "#/definitions/action_definition"
            }
          }
        }
      }
    },
    "locations": {
      "description": "List of locations that are available throughout the game",
      "type": "object",
      "additionalProperties": {
        "minProperties": 1,
        "type": "object",
        "required": ["objects"],
        "properties": {
          "objects": {
            "description": "List of objects in this location",
            "type": "array",
            "items": {
              "type": "string"
            },
            "uniqueItems": true
          }
        }
      }
    }
  },
  "required": ["general", "ignored_words", "verbs", "objects", "locations"]
}

=== Dak0r/TextAdventureJS/Templates/empty.tadb.json
{
  "$schema": "../textAdventureDatabase.schema.json",

  "general": {
    "title": "TextAdventureJS Empty Database Template",
    "author": "Your Name",
    "version": "0.1",
    "request": [ "", "What do you do?" ],
    "start": {
      "text": "Welcome to the Empty Template",
      "inventory": "",
      "action": [ "gotoLocation first_room" ]
    }
  },
  "ignored_words" :[ ],
  "verbs": {
  },
  "objects": {
  },
  "locations": {
    "first_room": {
      "objects": []
    }
  }
}
